# Generated by Django 5.2.6 on 2025-09-29 06:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg"],
                        "Только изображения формата png, jpg, jpeg",
                    )
                ],
                verbose_name="Аватар",
            ),
        ),
    ]
