# Generated by Django 5.2.6 on 2025-09-26 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("manage_cash", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Транзакции пользователя",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="manage_cash.statustransaction",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="subcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="manage_cash.subcategory",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="manage_cash.typetransaction",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="transaction_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="categories",
                to="manage_cash.typetransaction",
                verbose_name="Тип транзакции",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("name", "transaction_type")},
        ),
    ]
